### ISSUE TITLE
How to contact

### ISSUE THREAD

**Issue by nemchik** [justinhamlett/usenet-docker#6]
I'd like to reach out to you to chat about your project. I've got a similar project myself and was wondering if you'd like to chat and maybe put our heads together on a few things? My project has a discord server if you'd be interested https://discord.gg/YFyJpmH

Eric

**Comment by justinhamlett** [comment]
Hey Eric,

Sorry for the delayed reply, I stopped using gmail a year ago and never updated my github notifications to use my new email.

I definitely would love to chat about some ideas if you're still interested. Also I just joined dockstarter discord server.

**Comment by nemchik** [comment]
Sounds good! I'm ixnyne on discord. I need to plug my phone in to charge so I'll be offline for a bit, but we can chat when I get back!
